# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transaction.proto

import sys

_b = sys.version_info[0] < 3 and (lambda x: x) or (lambda x: x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor.FileDescriptor(
	name='transaction.proto',
	package='transaction',
	syntax='proto3',
	serialized_pb=_b(
		'\n\x11transaction.proto\x12\x0btransaction\"x\n\x10TransactionUsage\x12\x15\n\rcontract_uuid\x18\x01 \x01(\x0c\x12\x11\n\ttimestamp\x18\x02 \x01(\x04\x12\x13\n\x0b\x63onsumption\x18\x03 \x01(\x04\x12\x12\n\nproduction\x18\x04 \x01(\x04\x12\x11\n\tsignature\x18\x05 \x01(\x0c\"~\n\x16TransactionNewContract\x12\x0c\n\x04uuid\x18\x01 \x01(\x0c\x12\x11\n\ttimestamp\x18\x02 \x01(\x04\x12\x12\n\npublic_key\x18\x03 \x01(\x0c\x12\x11\n\tsignature\x18\x04 \x01(\x0c\x12\x1c\n\x14\x63ontractor_signature\x18\x05 \x01(\x0c\"N\n\x18TransactionCloseContract\x12\x0c\n\x04uuid\x18\x01 \x01(\x0c\x12\x11\n\ttimestamp\x18\x02 \x01(\x04\x12\x11\n\tsignature\x18\x03 \x01(\x0c\".\n\x19TransactionStartBalancing\x12\x11\n\ttimestamp\x18\x01 \x01(\x04\"\'\n\x12TransactionBalance\x12\x11\n\ttimestamp\x18\x01 \x01(\x04\",\n\x17TransactionEndBalancing\x12\x11\n\ttimestamp\x18\x01 \x01(\x04\"\xf6\x02\n\x0bTransaction\x12.\n\x05usage\x18\x01 \x01(\x0b\x32\x1d.transaction.TransactionUsageH\x00\x12;\n\x0cnew_contract\x18\x02 \x01(\x0b\x32#.transaction.TransactionNewContractH\x00\x12?\n\x0e\x63lose_contract\x18\x03 \x01(\x0b\x32%.transaction.TransactionCloseContractH\x00\x12?\n\rbalance_start\x18\x04 \x01(\x0b\x32&.transaction.TransactionStartBalancingH\x00\x12\x32\n\x07\x62\x61lance\x18\x05 \x01(\x0b\x32\x1f.transaction.TransactionBalanceH\x00\x12;\n\x0b\x62\x61lance_end\x18\x06 \x01(\x0b\x32$.transaction.TransactionEndBalancingH\x00\x42\x07\n\x05valueb\x06proto3')
)

_TRANSACTIONUSAGE = _descriptor.Descriptor(
	name='TransactionUsage',
	full_name='transaction.TransactionUsage',
	filename=None,
	file=DESCRIPTOR,
	containing_type=None,
	fields=[
		_descriptor.FieldDescriptor(
			name='contract_uuid', full_name='transaction.TransactionUsage.contract_uuid', index=0,
			number=1, type=12, cpp_type=9, label=1,
			has_default_value=False, default_value=_b(""),
			message_type=None, enum_type=None, containing_type=None,
			is_extension=False, extension_scope=None,
			options=None, file=DESCRIPTOR),
		_descriptor.FieldDescriptor(
			name='timestamp', full_name='transaction.TransactionUsage.timestamp', index=1,
			number=2, type=4, cpp_type=4, label=1,
			has_default_value=False, default_value=0,
			message_type=None, enum_type=None, containing_type=None,
			is_extension=False, extension_scope=None,
			options=None, file=DESCRIPTOR),
		_descriptor.FieldDescriptor(
			name='consumption', full_name='transaction.TransactionUsage.consumption', index=2,
			number=3, type=4, cpp_type=4, label=1,
			has_default_value=False, default_value=0,
			message_type=None, enum_type=None, containing_type=None,
			is_extension=False, extension_scope=None,
			options=None, file=DESCRIPTOR),
		_descriptor.FieldDescriptor(
			name='production', full_name='transaction.TransactionUsage.production', index=3,
			number=4, type=4, cpp_type=4, label=1,
			has_default_value=False, default_value=0,
			message_type=None, enum_type=None, containing_type=None,
			is_extension=False, extension_scope=None,
			options=None, file=DESCRIPTOR),
		_descriptor.FieldDescriptor(
			name='signature', full_name='transaction.TransactionUsage.signature', index=4,
			number=5, type=12, cpp_type=9, label=1,
			has_default_value=False, default_value=_b(""),
			message_type=None, enum_type=None, containing_type=None,
			is_extension=False, extension_scope=None,
			options=None, file=DESCRIPTOR),
	],
	extensions=[
	],
	nested_types=[],
	enum_types=[
	],
	options=None,
	is_extendable=False,
	syntax='proto3',
	extension_ranges=[],
	oneofs=[
	],
	serialized_start=34,
	serialized_end=154,
)

_TRANSACTIONNEWCONTRACT = _descriptor.Descriptor(
	name='TransactionNewContract',
	full_name='transaction.TransactionNewContract',
	filename=None,
	file=DESCRIPTOR,
	containing_type=None,
	fields=[
		_descriptor.FieldDescriptor(
			name='uuid', full_name='transaction.TransactionNewContract.uuid', index=0,
			number=1, type=12, cpp_type=9, label=1,
			has_default_value=False, default_value=_b(""),
			message_type=None, enum_type=None, containing_type=None,
			is_extension=False, extension_scope=None,
			options=None, file=DESCRIPTOR),
		_descriptor.FieldDescriptor(
			name='timestamp', full_name='transaction.TransactionNewContract.timestamp', index=1,
			number=2, type=4, cpp_type=4, label=1,
			has_default_value=False, default_value=0,
			message_type=None, enum_type=None, containing_type=None,
			is_extension=False, extension_scope=None,
			options=None, file=DESCRIPTOR),
		_descriptor.FieldDescriptor(
			name='public_key', full_name='transaction.TransactionNewContract.public_key', index=2,
			number=3, type=12, cpp_type=9, label=1,
			has_default_value=False, default_value=_b(""),
			message_type=None, enum_type=None, containing_type=None,
			is_extension=False, extension_scope=None,
			options=None, file=DESCRIPTOR),
		_descriptor.FieldDescriptor(
			name='signature', full_name='transaction.TransactionNewContract.signature', index=3,
			number=4, type=12, cpp_type=9, label=1,
			has_default_value=False, default_value=_b(""),
			message_type=None, enum_type=None, containing_type=None,
			is_extension=False, extension_scope=None,
			options=None, file=DESCRIPTOR),
		_descriptor.FieldDescriptor(
			name='contractor_signature', full_name='transaction.TransactionNewContract.contractor_signature', index=4,
			number=5, type=12, cpp_type=9, label=1,
			has_default_value=False, default_value=_b(""),
			message_type=None, enum_type=None, containing_type=None,
			is_extension=False, extension_scope=None,
			options=None, file=DESCRIPTOR),
	],
	extensions=[
	],
	nested_types=[],
	enum_types=[
	],
	options=None,
	is_extendable=False,
	syntax='proto3',
	extension_ranges=[],
	oneofs=[
	],
	serialized_start=156,
	serialized_end=282,
)

_TRANSACTIONCLOSECONTRACT = _descriptor.Descriptor(
	name='TransactionCloseContract',
	full_name='transaction.TransactionCloseContract',
	filename=None,
	file=DESCRIPTOR,
	containing_type=None,
	fields=[
		_descriptor.FieldDescriptor(
			name='uuid', full_name='transaction.TransactionCloseContract.uuid', index=0,
			number=1, type=12, cpp_type=9, label=1,
			has_default_value=False, default_value=_b(""),
			message_type=None, enum_type=None, containing_type=None,
			is_extension=False, extension_scope=None,
			options=None, file=DESCRIPTOR),
		_descriptor.FieldDescriptor(
			name='timestamp', full_name='transaction.TransactionCloseContract.timestamp', index=1,
			number=2, type=4, cpp_type=4, label=1,
			has_default_value=False, default_value=0,
			message_type=None, enum_type=None, containing_type=None,
			is_extension=False, extension_scope=None,
			options=None, file=DESCRIPTOR),
		_descriptor.FieldDescriptor(
			name='signature', full_name='transaction.TransactionCloseContract.signature', index=2,
			number=3, type=12, cpp_type=9, label=1,
			has_default_value=False, default_value=_b(""),
			message_type=None, enum_type=None, containing_type=None,
			is_extension=False, extension_scope=None,
			options=None, file=DESCRIPTOR),
	],
	extensions=[
	],
	nested_types=[],
	enum_types=[
	],
	options=None,
	is_extendable=False,
	syntax='proto3',
	extension_ranges=[],
	oneofs=[
	],
	serialized_start=284,
	serialized_end=362,
)

_TRANSACTIONSTARTBALANCING = _descriptor.Descriptor(
	name='TransactionStartBalancing',
	full_name='transaction.TransactionStartBalancing',
	filename=None,
	file=DESCRIPTOR,
	containing_type=None,
	fields=[
		_descriptor.FieldDescriptor(
			name='timestamp', full_name='transaction.TransactionStartBalancing.timestamp', index=0,
			number=1, type=4, cpp_type=4, label=1,
			has_default_value=False, default_value=0,
			message_type=None, enum_type=None, containing_type=None,
			is_extension=False, extension_scope=None,
			options=None, file=DESCRIPTOR),
	],
	extensions=[
	],
	nested_types=[],
	enum_types=[
	],
	options=None,
	is_extendable=False,
	syntax='proto3',
	extension_ranges=[],
	oneofs=[
	],
	serialized_start=364,
	serialized_end=410,
)

_TRANSACTIONBALANCE = _descriptor.Descriptor(
	name='TransactionBalance',
	full_name='transaction.TransactionBalance',
	filename=None,
	file=DESCRIPTOR,
	containing_type=None,
	fields=[
		_descriptor.FieldDescriptor(
			name='timestamp', full_name='transaction.TransactionBalance.timestamp', index=0,
			number=1, type=4, cpp_type=4, label=1,
			has_default_value=False, default_value=0,
			message_type=None, enum_type=None, containing_type=None,
			is_extension=False, extension_scope=None,
			options=None, file=DESCRIPTOR),
	],
	extensions=[
	],
	nested_types=[],
	enum_types=[
	],
	options=None,
	is_extendable=False,
	syntax='proto3',
	extension_ranges=[],
	oneofs=[
	],
	serialized_start=412,
	serialized_end=451,
)

_TRANSACTIONENDBALANCING = _descriptor.Descriptor(
	name='TransactionEndBalancing',
	full_name='transaction.TransactionEndBalancing',
	filename=None,
	file=DESCRIPTOR,
	containing_type=None,
	fields=[
		_descriptor.FieldDescriptor(
			name='timestamp', full_name='transaction.TransactionEndBalancing.timestamp', index=0,
			number=1, type=4, cpp_type=4, label=1,
			has_default_value=False, default_value=0,
			message_type=None, enum_type=None, containing_type=None,
			is_extension=False, extension_scope=None,
			options=None, file=DESCRIPTOR),
	],
	extensions=[
	],
	nested_types=[],
	enum_types=[
	],
	options=None,
	is_extendable=False,
	syntax='proto3',
	extension_ranges=[],
	oneofs=[
	],
	serialized_start=453,
	serialized_end=497,
)

_TRANSACTION = _descriptor.Descriptor(
	name='Transaction',
	full_name='transaction.Transaction',
	filename=None,
	file=DESCRIPTOR,
	containing_type=None,
	fields=[
		_descriptor.FieldDescriptor(
			name='usage', full_name='transaction.Transaction.usage', index=0,
			number=1, type=11, cpp_type=10, label=1,
			has_default_value=False, default_value=None,
			message_type=None, enum_type=None, containing_type=None,
			is_extension=False, extension_scope=None,
			options=None, file=DESCRIPTOR),
		_descriptor.FieldDescriptor(
			name='new_contract', full_name='transaction.Transaction.new_contract', index=1,
			number=2, type=11, cpp_type=10, label=1,
			has_default_value=False, default_value=None,
			message_type=None, enum_type=None, containing_type=None,
			is_extension=False, extension_scope=None,
			options=None, file=DESCRIPTOR),
		_descriptor.FieldDescriptor(
			name='close_contract', full_name='transaction.Transaction.close_contract', index=2,
			number=3, type=11, cpp_type=10, label=1,
			has_default_value=False, default_value=None,
			message_type=None, enum_type=None, containing_type=None,
			is_extension=False, extension_scope=None,
			options=None, file=DESCRIPTOR),
		_descriptor.FieldDescriptor(
			name='balance_start', full_name='transaction.Transaction.balance_start', index=3,
			number=4, type=11, cpp_type=10, label=1,
			has_default_value=False, default_value=None,
			message_type=None, enum_type=None, containing_type=None,
			is_extension=False, extension_scope=None,
			options=None, file=DESCRIPTOR),
		_descriptor.FieldDescriptor(
			name='balance', full_name='transaction.Transaction.balance', index=4,
			number=5, type=11, cpp_type=10, label=1,
			has_default_value=False, default_value=None,
			message_type=None, enum_type=None, containing_type=None,
			is_extension=False, extension_scope=None,
			options=None, file=DESCRIPTOR),
		_descriptor.FieldDescriptor(
			name='balance_end', full_name='transaction.Transaction.balance_end', index=5,
			number=6, type=11, cpp_type=10, label=1,
			has_default_value=False, default_value=None,
			message_type=None, enum_type=None, containing_type=None,
			is_extension=False, extension_scope=None,
			options=None, file=DESCRIPTOR),
	],
	extensions=[
	],
	nested_types=[],
	enum_types=[
	],
	options=None,
	is_extendable=False,
	syntax='proto3',
	extension_ranges=[],
	oneofs=[
		_descriptor.OneofDescriptor(
			name='value', full_name='transaction.Transaction.value',
			index=0, containing_type=None, fields=[]),
	],
	serialized_start=500,
	serialized_end=874,
)

_TRANSACTION.fields_by_name['usage'].message_type = _TRANSACTIONUSAGE
_TRANSACTION.fields_by_name['new_contract'].message_type = _TRANSACTIONNEWCONTRACT
_TRANSACTION.fields_by_name['close_contract'].message_type = _TRANSACTIONCLOSECONTRACT
_TRANSACTION.fields_by_name['balance_start'].message_type = _TRANSACTIONSTARTBALANCING
_TRANSACTION.fields_by_name['balance'].message_type = _TRANSACTIONBALANCE
_TRANSACTION.fields_by_name['balance_end'].message_type = _TRANSACTIONENDBALANCING
_TRANSACTION.oneofs_by_name['value'].fields.append(
	_TRANSACTION.fields_by_name['usage'])
_TRANSACTION.fields_by_name['usage'].containing_oneof = _TRANSACTION.oneofs_by_name['value']
_TRANSACTION.oneofs_by_name['value'].fields.append(
	_TRANSACTION.fields_by_name['new_contract'])
_TRANSACTION.fields_by_name['new_contract'].containing_oneof = _TRANSACTION.oneofs_by_name['value']
_TRANSACTION.oneofs_by_name['value'].fields.append(
	_TRANSACTION.fields_by_name['close_contract'])
_TRANSACTION.fields_by_name['close_contract'].containing_oneof = _TRANSACTION.oneofs_by_name['value']
_TRANSACTION.oneofs_by_name['value'].fields.append(
	_TRANSACTION.fields_by_name['balance_start'])
_TRANSACTION.fields_by_name['balance_start'].containing_oneof = _TRANSACTION.oneofs_by_name['value']
_TRANSACTION.oneofs_by_name['value'].fields.append(
	_TRANSACTION.fields_by_name['balance'])
_TRANSACTION.fields_by_name['balance'].containing_oneof = _TRANSACTION.oneofs_by_name['value']
_TRANSACTION.oneofs_by_name['value'].fields.append(
	_TRANSACTION.fields_by_name['balance_end'])
_TRANSACTION.fields_by_name['balance_end'].containing_oneof = _TRANSACTION.oneofs_by_name['value']
DESCRIPTOR.message_types_by_name['TransactionUsage'] = _TRANSACTIONUSAGE
DESCRIPTOR.message_types_by_name['TransactionNewContract'] = _TRANSACTIONNEWCONTRACT
DESCRIPTOR.message_types_by_name['TransactionCloseContract'] = _TRANSACTIONCLOSECONTRACT
DESCRIPTOR.message_types_by_name['TransactionStartBalancing'] = _TRANSACTIONSTARTBALANCING
DESCRIPTOR.message_types_by_name['TransactionBalance'] = _TRANSACTIONBALANCE
DESCRIPTOR.message_types_by_name['TransactionEndBalancing'] = _TRANSACTIONENDBALANCING
DESCRIPTOR.message_types_by_name['Transaction'] = _TRANSACTION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TransactionUsage = _reflection.GeneratedProtocolMessageType('TransactionUsage', (_message.Message,), dict(
	DESCRIPTOR=_TRANSACTIONUSAGE,
	__module__='transaction_pb2'
	# @@protoc_insertion_point(class_scope:transaction.TransactionUsage)
))
_sym_db.RegisterMessage(TransactionUsage)

TransactionNewContract = _reflection.GeneratedProtocolMessageType('TransactionNewContract', (_message.Message,), dict(
	DESCRIPTOR=_TRANSACTIONNEWCONTRACT,
	__module__='transaction_pb2'
	# @@protoc_insertion_point(class_scope:transaction.TransactionNewContract)
))
_sym_db.RegisterMessage(TransactionNewContract)

TransactionCloseContract = _reflection.GeneratedProtocolMessageType('TransactionCloseContract', (_message.Message,),
																	dict(
																		DESCRIPTOR=_TRANSACTIONCLOSECONTRACT,
																		__module__='transaction_pb2'
																		# @@protoc_insertion_point(class_scope:transaction.TransactionCloseContract)
																	))
_sym_db.RegisterMessage(TransactionCloseContract)

TransactionStartBalancing = _reflection.GeneratedProtocolMessageType('TransactionStartBalancing', (_message.Message,),
																	 dict(
																		 DESCRIPTOR=_TRANSACTIONSTARTBALANCING,
																		 __module__='transaction_pb2'
																		 # @@protoc_insertion_point(class_scope:transaction.TransactionStartBalancing)
																	 ))
_sym_db.RegisterMessage(TransactionStartBalancing)

TransactionBalance = _reflection.GeneratedProtocolMessageType('TransactionBalance', (_message.Message,), dict(
	DESCRIPTOR=_TRANSACTIONBALANCE,
	__module__='transaction_pb2'
	# @@protoc_insertion_point(class_scope:transaction.TransactionBalance)
))
_sym_db.RegisterMessage(TransactionBalance)

TransactionEndBalancing = _reflection.GeneratedProtocolMessageType('TransactionEndBalancing', (_message.Message,), dict(
	DESCRIPTOR=_TRANSACTIONENDBALANCING,
	__module__='transaction_pb2'
	# @@protoc_insertion_point(class_scope:transaction.TransactionEndBalancing)
))
_sym_db.RegisterMessage(TransactionEndBalancing)

Transaction = _reflection.GeneratedProtocolMessageType('Transaction', (_message.Message,), dict(
	DESCRIPTOR=_TRANSACTION,
	__module__='transaction_pb2'
	# @@protoc_insertion_point(class_scope:transaction.Transaction)
))
_sym_db.RegisterMessage(Transaction)

# @@protoc_insertion_point(module_scope)
